#!/usr/bin/env node
// SPDX-FileCopyrightText: 2026 Numen Games S.L.
// SPDX-License-Identifier: AGPL-3.0-only
//
// Design tokens → src/styles/tokens.css
//
// The source of every colour, radius and curve is the installed package
// @numengames/design-kit (numinia-nwos, packages/design-kit/). This script
// reads its token file and writes the CSS custom properties Tailwind consumes
// (RGB triplets, so `bg-bg/50` can apply opacity). Nothing here is typed by
// hand: STD-008 DSN-009 — the kit is installed, never copied.
//
//   node scripts/design-tokens.mjs           # write src/styles/tokens.css
//   node scripts/design-tokens.mjs --check   # exit 1 if the file is stale
//
// Runs as `predev`/`prebuild`, so a bumped package regenerates the file and a
// hand edit is overwritten on the next build.

import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const TOKENS = require.resolve("@numengames/design-kit/sistema.tokens.json");
const PKG = JSON.parse(fs.readFileSync(path.join(path.dirname(TOKENS), "package.json"), "utf8"));
const OUT = path.resolve("src/styles/tokens.css");
const CHECK = process.argv.includes("--check");

const t = JSON.parse(fs.readFileSync(TOKENS, "utf8"));
const get = (p) => {
	const node = p.split(".").reduce((o, k) => (o == null ? undefined : o[k]), t);
	if (node == null || node.$value === undefined) throw new Error(`token missing: ${p}`);
	return node.$value;
};
const rgb = (hex) => {
	const h = hex.replace("#", "");
	return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(" ");
};

/* CSS variable ← token path. The left side is this repo's vocabulary
   (Tailwind config); the right side is the kit's. Aliases stay aliases. */
const COLORS = {
	"--bg": "color.nocturno.fondo-base",
	"--bg-card": "color.nocturno.fondo-superficie",
	"--bg-card-hover": "color.nocturno.fondo-elevada",
	"--border": "color.nocturno.linea-fuerte",
	"--border-soft": "color.nocturno.linea-tenue",
	"--text": "color.nocturno.texto-primario",
	"--text-muted": "color.nocturno.texto-secundario",
	"--text-dim": "color.nocturno.texto-terciario",
	"--accent": "color.enlace.nocturno",
	"--interactivo": "color.interactivo.fondo",
	"--interactivo-hover": "color.interactivo.hover",
	"--interactivo-activo": "color.interactivo.activo",
	"--verdemar": "color.marca.verdemar",
	"--turquesa": "color.marca.turquesa",
	"--ambar": "color.marca.ambar",
	"--arena": "color.marca.arena",
	"--coral": "color.marca.coral",
	"--grana": "color.marca.grana",
	// Inherited flavour names: each holds the token that occupies its role.
	"--terracota": "color.marca.ambar",
	"--ocre": "color.marca.ambar",
	"--cobre": "color.marca.ambar",
	"--bronce": "color.nocturno.texto-terciario",
	"--teal": "color.marca.turquesa",
};
/* --blue and --purple were copied from the rarity scale (raro, épico). STD-023
   says rarity never colours data; they keep their value so nothing breaks, but
   any use of them as a data colour is a breach to fix here, not in the kit. */
const DATA_VARS = {
	"--green": "color.rareza.poco-comun",
	"--red": "color.marca.grana",
	"--yellow": "color.marca.ambar",
	"--blue": "color.rareza.raro",
	"--purple": "color.rareza.epico",
	"--salvia": "color.rareza.poco-comun",
	"--azul-med": "color.rareza.raro",
};

let css = `/* SPDX-FileCopyrightText: 2026 Numen Games S.L. */
/* SPDX-License-Identifier: AGPL-3.0-only */
/* GENERATED by scripts/design-tokens.mjs from @numengames/design-kit ${PKG.version}.
 * Do not edit: the source is packages/design-kit/ in numinia-nwos (ADR-044).
 * Registro Umbral · modo Nocturno. RGB triplets so Tailwind can apply opacity. */
:root {
`;
for (const [v, p] of Object.entries(COLORS)) css += `\t${v}: ${rgb(get(p))}; /* ${get(p)} */\n`;
css += `\n\t/* Data and inherited flavour names */\n`;
for (const [v, p] of Object.entries(DATA_VARS)) css += `\t${v}: ${rgb(get(p))}; /* ${get(p)} */\n`;
css += `\n\t/* Atmósfera del Velo · solo alfa sobre canónicos */\n`;
css += `\t--accent-glow: rgba(${rgb(get("color.marca.turquesa")).replaceAll(" ", ", ")}, 0.08);\n`;
css += `\t--veil-glow: rgba(${rgb(get("color.marca.turquesa")).replaceAll(" ", ", ")}, 0.06);\n`;
css += `\t--cobre-glow: rgba(${rgb(get("color.marca.ambar")).replaceAll(" ", ", ")}, 0.18);\n`;
css += `\n\t/* Escala de rareza (color.rareza) · nunca colorea datos */\n`;
for (const k of ["comun", "poco-comun", "raro", "epico", "legendario"]) css += `\t--rareza-${k}: ${rgb(get(`color.rareza.${k}`))}; /* ${get(`color.rareza.${k}`)} */\n`;
css += `\n\t/* Forma · dos radios y solo dos */\n`;
css += `\t--radius: ${get("borderRadius.marco")};\n\t--radius-control: ${get("borderRadius.control")};\n`;
const cb = get("cubicBezier.ciclo");
css += `\t--ciclo: cubic-bezier(${Array.isArray(cb) ? cb.join(", ") : cb});\n}\n`;

if (CHECK) {
	const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
	if (cur !== css) {
		console.error(`design-tokens: ${path.relative(".", OUT)} is stale — run node scripts/design-tokens.mjs`);
		process.exit(1);
	}
	console.log(`design-tokens: ${path.relative(".", OUT)} matches @numengames/design-kit ${PKG.version}.`);
} else {
	fs.writeFileSync(OUT, css);
	console.log(`design-tokens: wrote ${path.relative(".", OUT)} from @numengames/design-kit ${PKG.version}.`);
}
